### ISSUE TITLE
테이블 유니크 키 및 인덱스 추가

### ISSUE THREAD

**Issue by rerewww** [yeen28/voa#24]
[작업 내용]
- 엔티티 클래스에서 유니크 키 및 인덱스를 적용해야 합니다.

**Comment by yeen28** [comment]
인덱스는 조회를 하는 엔티티 모두에 추가하는 건가요??

**Comment by rerewww** [comment]
자주 조회하거나 조회할 양이 많을 테이블에 인덱스를 걸어두고 작업하면서 인덱스를 추가해보져

**Comment by yeen28** [comment]
좋아여
