### ISSUE TITLE
예외 처리를 일괄적으로 처리 할 수 있는 방법 검토 및 적용

### ISSUE THREAD

**Issue by rerewww** [yeen28/voa#52]
#### [작업 내용]
컨트롤러에서 try-catch로 코드가 적용되어 있어 중복되거나 비슷한 try-catch 구문이 많습니다.
예를 들어 이슈 조회나 이슈 업데이트를 보면 

```
try {
   // 이슈 조회
} catch (EntityNotFoundException e) {
   return new Response... 
}
```

위와 같은 코드 스타일을 제거하기 위해 익셉션을 일괄적으로 처리 할 수 있는 방법을 찾아서 적용해야 합니다.

[기대 결과]
컨트롤러을 통해 익셉션이 발생하면 모 클래스에서 익셉션을 받아서 클라이언트로 에러 코드 및 에러 모델을 반환해야 합니다.

**Comment by yeen28** [comment]
🫡
