### ISSUE TITLE
[서버] 젠킨스로 빌드 자동화 구축

### ISSUE THREAD

**Issue by rerewww** [yeen28/voa#56]
#### [작업 내용]
- 젠킨스를 이용하여 빌드 자동화 구축하기

**Comment by yeen28** [comment]
![image](https://github.com/yeen28/voa/assets/48883549/0726fd05-e5d4-49c6-bae1-c7e3d8447bb0)
설치해서 이렇게 확인은 했는데 깃헙 웹훅은 local말고 URL이 있어야 한다고 해서 그건 안됐어요

**Comment by rerewww** [comment]
젠킨스로 테스트부터 빌드까지 한 턴을 돌려서 경험을 목적으로 만든 이슈여서 여기서 이슈 정리하겠습니다. b
